port: 3000
requiredModules:
  - core
  - agent
  - executor
  - planner
  - llm
  - data
command: agent.mainLoop
containers:
- modules:
    core: './modules/core'
    agent: './modules/agent'
    executor: './modules/executor'
    planner: './modules/planner/TreePlanner'
    llm:
      from: './modules/llm/openai'
      settings:
        apiKey: ${OPENAI_API_KEY}
        model: gpt-4
    data:
      from: './modules/data/sqlite'
      settings:
        database: data.db

