openapi: 3.0.2
info:
  title: AGI Toolkit - LLM Module
  description: A module for AGI Toolkit to interface with a LLM
  version: 1.0.0
basePath: /module
paths:
  /llm:
    post:
      summary: Query
      description:
      # operationId: query_query_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
components:
  schemas:
    PromptRequest:
      title: PromptRrequest
      type: object
      properties:
        context:
          title: Context
          items:
            type: string
        prompt:
          title: Prompt
          type: string
    PromptResponse:
      title: PromptResponse
      required:
        - result
      type: object
      properties:
        result:
          title: Result
          type: string
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
